import type { Workspace } from '@/types/model'

/** Big Bank plc — classic Structurizr example workspace */
export function createBigBankSample(): Workspace {
  return {
    name: 'Big Bank plc',
    description: 'A model of the Big Bank plc software system landscape.',
    model: {
      people: [
        {
          id: 'customer',
          type: 'person',
          name: 'Personal Banking Customer',
          description: 'A customer of the bank, with personal bank accounts.',
          tags: ['Element', 'Person', 'Customer'],
          properties: {},
          location: 'External',
        },
        {
          id: 'supportStaff',
          type: 'person',
          name: 'Customer Service Staff',
          description: 'Customer service staff within the bank.',
          tags: ['Element', 'Person', 'Bank Staff'],
          properties: {},
          location: 'Internal',
        },
        {
          id: 'backoffice',
          type: 'person',
          name: 'Back Office Staff',
          description: 'Administration and support staff within the bank.',
          tags: ['Element', 'Person', 'Bank Staff'],
          properties: {},
          location: 'Internal',
        },
      ],
      softwareSystems: [
        {
          id: 'internetBanking',
          type: 'softwareSystem',
          name: 'Internet Banking System',
          description: 'Allows customers to view information about their bank accounts, and make payments.',
          tags: ['Element', 'Software System'],
          properties: {},
          location: 'Internal',
          containers: [
            {
              id: 'singlePageApp',
              type: 'container',
              name: 'Single-Page Application',
              description: 'Provides all of the Internet banking functionality to customers via their web browser.',
              technology: 'JavaScript, Angular',
              tags: ['Element', 'Container'],
              properties: {},
              components: [],
            },
            {
              id: 'mobileApp',
              type: 'container',
              name: 'Mobile App',
              description: 'Provides a limited subset of the Internet banking functionality to customers via their mobile device.',
              technology: 'Xamarin',
              tags: ['Element', 'Container'],
              properties: {},
              components: [],
            },
            {
              id: 'webApp',
              type: 'container',
              name: 'Web Application',
              description: 'Delivers the single page application.',
              technology: 'Java, Spring MVC',
              tags: ['Element', 'Container'],
              properties: {},
              components: [],
            },
            {
              id: 'apiApp',
              type: 'container',
              name: 'API Application',
              description: 'Provides Internet banking functionality via a JSON/HTTPS API.',
              technology: 'Java, Spring MVC',
              tags: ['Element', 'Container'],
              properties: {},
              components: [
                {
                  id: 'signinController',
                  type: 'component',
                  name: 'Sign In Controller',
                  description: 'Allows users to sign in to the Internet Banking System.',
                  technology: 'Spring MVC Controller',
                  tags: ['Element', 'Component'],
                  properties: {},
                },
                {
                  id: 'resetPassController',
                  type: 'component',
                  name: 'Reset Password Controller',
                  description: 'Allows users to reset their passwords.',
                  technology: 'Spring MVC Controller',
                  tags: ['Element', 'Component'],
                  properties: {},
                },
                {
                  id: 'accountsSummary',
                  type: 'component',
                  name: 'Accounts Summary Controller',
                  description: 'Provides customers with a summary of their bank accounts.',
                  technology: 'Spring MVC Controller',
                  tags: ['Element', 'Component'],
                  properties: {},
                },
                {
                  id: 'securityComponent',
                  type: 'component',
                  name: 'Security Component',
                  description: 'Provides functionality related to signing in, changing passwords, etc.',
                  technology: 'Spring Bean',
                  tags: ['Element', 'Component'],
                  properties: {},
                },
                {
                  id: 'emailComponent',
                  type: 'component',
                  name: 'E-mail Component',
                  description: 'Sends e-mails to users.',
                  technology: 'Spring Bean',
                  tags: ['Element', 'Component'],
                  properties: {},
                },
                {
                  id: 'mainframeFacade',
                  type: 'component',
                  name: 'Mainframe Banking System Facade',
                  description: 'A facade onto the mainframe banking system.',
                  technology: 'Spring Bean',
                  tags: ['Element', 'Component'],
                  properties: {},
                },
              ],
            },
            {
              id: 'database',
              type: 'container',
              name: 'Database',
              description: 'Stores user registration information, hashed authentication credentials, access logs, etc.',
              technology: 'Oracle 12c',
              tags: ['Element', 'Container', 'Database'],
              properties: {},
              components: [],
            },
          ],
        },
        {
          id: 'mainframe',
          type: 'softwareSystem',
          name: 'Mainframe Banking System',
          description: 'Stores all of the core banking information about customers, accounts, transactions, etc.',
          tags: ['Element', 'Software System', 'Existing System'],
          properties: {},
          location: 'Internal',
          containers: [],
        },
        {
          id: 'email',
          type: 'softwareSystem',
          name: 'E-mail System',
          description: 'The internal Microsoft Exchange e-mail system.',
          tags: ['Element', 'Software System', 'Existing System'],
          properties: {},
          location: 'Internal',
          containers: [],
        },
        {
          id: 'atm',
          type: 'softwareSystem',
          name: 'ATM',
          description: 'Allows customers to withdraw cash.',
          tags: ['Element', 'Software System', 'Existing System'],
          properties: {},
          location: 'Internal',
          containers: [],
        },
      ],
      relationships: [
        // System landscape level
        { id: 'r1', sourceId: 'customer', destinationId: 'internetBanking', description: 'Views account balances and makes payments', tags: ['Relationship'], properties: {} },
        { id: 'r2', sourceId: 'internetBanking', destinationId: 'mainframe', description: 'Gets account information from', tags: ['Relationship'], properties: {} },
        { id: 'r3', sourceId: 'internetBanking', destinationId: 'email', description: 'Sends e-mail using', tags: ['Relationship'], properties: {} },
        { id: 'r4', sourceId: 'email', destinationId: 'customer', description: 'Sends e-mails to', tags: ['Relationship'], properties: {} },
        { id: 'r5', sourceId: 'customer', destinationId: 'supportStaff', description: 'Asks questions to', technology: 'Telephone', tags: ['Relationship'], properties: {} },
        { id: 'r6', sourceId: 'supportStaff', destinationId: 'mainframe', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r7', sourceId: 'customer', destinationId: 'atm', description: 'Withdraws cash', tags: ['Relationship'], properties: {} },
        { id: 'r8', sourceId: 'atm', destinationId: 'mainframe', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r9', sourceId: 'backoffice', destinationId: 'mainframe', description: 'Uses', tags: ['Relationship'], properties: {} },
        // Container level
        { id: 'r10', sourceId: 'customer', destinationId: 'webApp', description: 'Visits', technology: 'HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r11', sourceId: 'customer', destinationId: 'singlePageApp', description: 'Views and interacts', tags: ['Relationship'], properties: {} },
        { id: 'r12', sourceId: 'customer', destinationId: 'mobileApp', description: 'Views and interacts', tags: ['Relationship'], properties: {} },
        { id: 'r13', sourceId: 'webApp', destinationId: 'singlePageApp', description: 'Delivers', tags: ['Relationship'], properties: {} },
        { id: 'r14', sourceId: 'singlePageApp', destinationId: 'apiApp', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r15', sourceId: 'mobileApp', destinationId: 'apiApp', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r16', sourceId: 'apiApp', destinationId: 'database', description: 'Reads from and writes to', technology: 'JDBC', tags: ['Relationship'], properties: {} },
        { id: 'r17', sourceId: 'apiApp', destinationId: 'mainframe', description: 'Makes API calls', technology: 'XML/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r18', sourceId: 'apiApp', destinationId: 'email', description: 'Sends e-mail using', technology: 'SMTP', tags: ['Relationship'], properties: {} },
        // Component level
        { id: 'r19', sourceId: 'singlePageApp', destinationId: 'signinController', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r20', sourceId: 'singlePageApp', destinationId: 'resetPassController', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r21', sourceId: 'singlePageApp', destinationId: 'accountsSummary', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r22', sourceId: 'signinController', destinationId: 'securityComponent', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r23', sourceId: 'resetPassController', destinationId: 'securityComponent', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r24', sourceId: 'resetPassController', destinationId: 'emailComponent', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r25', sourceId: 'accountsSummary', destinationId: 'mainframeFacade', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r26', sourceId: 'securityComponent', destinationId: 'database', description: 'Reads from and writes to', technology: 'JDBC', tags: ['Relationship'], properties: {} },
        { id: 'r27', sourceId: 'emailComponent', destinationId: 'email', description: 'Sends e-mail using', technology: 'SMTP', tags: ['Relationship'], properties: {} },
        { id: 'r28', sourceId: 'mainframeFacade', destinationId: 'mainframe', description: 'Makes API calls', technology: 'XML/HTTPS', tags: ['Relationship'], properties: {} },
      ],
      groups: [],
    },
    views: {
      systemLandscapeViews: [
        {
          type: 'systemLandscape',
          key: 'SystemLandscape',
          title: 'System Landscape',
          description: 'The system landscape for Big Bank plc.',
          elements: [
            { id: 'customer' },
            { id: 'internetBanking' },
            { id: 'mainframe' },
            { id: 'email' },
            { id: 'atm' },
            { id: 'supportStaff' },
            { id: 'backoffice' },
          ],
          relationships: [
            { id: 'r1' }, { id: 'r2' }, { id: 'r3' }, { id: 'r4' },
            { id: 'r5' }, { id: 'r6' }, { id: 'r7' }, { id: 'r8' }, { id: 'r9' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      systemContextViews: [
        {
          type: 'systemContext',
          key: 'SystemContext',
          title: 'System Context',
          description: 'The system context for Internet Banking.',
          softwareSystemId: 'internetBanking',
          elements: [
            { id: 'customer' },
            { id: 'internetBanking' },
            { id: 'mainframe' },
            { id: 'email' },
          ],
          relationships: [
            { id: 'r1' }, { id: 'r2' }, { id: 'r3' }, { id: 'r4' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      containerViews: [
        {
          type: 'container',
          key: 'Containers',
          title: 'Containers',
          description: 'The containers within Internet Banking.',
          softwareSystemId: 'internetBanking',
          elements: [
            { id: 'customer' },
            { id: 'singlePageApp' },
            { id: 'mobileApp' },
            { id: 'webApp' },
            { id: 'apiApp' },
            { id: 'database' },
            { id: 'mainframe' },
            { id: 'email' },
          ],
          relationships: [
            { id: 'r10' }, { id: 'r11' }, { id: 'r12' }, { id: 'r13' },
            { id: 'r14' }, { id: 'r15' }, { id: 'r16' }, { id: 'r17' }, { id: 'r18' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      componentViews: [
        {
          type: 'component',
          key: 'Components',
          title: 'Components',
          description: 'The components within the API Application.',
          containerId: 'apiApp',
          elements: [
            { id: 'singlePageApp' },
            { id: 'signinController' },
            { id: 'resetPassController' },
            { id: 'accountsSummary' },
            { id: 'securityComponent' },
            { id: 'emailComponent' },
            { id: 'mainframeFacade' },
            { id: 'database' },
            { id: 'email' },
            { id: 'mainframe' },
          ],
          relationships: [
            { id: 'r19' }, { id: 'r20' }, { id: 'r21' }, { id: 'r22' },
            { id: 'r23' }, { id: 'r24' }, { id: 'r25' }, { id: 'r26' },
            { id: 'r27' }, { id: 'r28' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      configuration: {
        styles: {
          elements: [
            { tag: 'Bank Staff', background: '#1e2832', color: '#94a3b8', stroke: '#475569' },
            { tag: 'Existing System', background: '#2a2018', color: '#d4a96a', stroke: '#a37032' },
            { tag: 'Database', background: '#1e1a40', color: '#c4b5fd', stroke: '#7c3aed', shape: 'Cylinder' },
          ],
          relationships: [],
        },
      },
    },
  }
}
