import type { Workspace } from '@/types/model'

/** Event-driven architecture — producers, Kafka, consumers, data lake */
export function createEventDrivenTemplate(): Workspace {
  return {
    name: 'Event-Driven Architecture',
    description: 'An event-driven system with producer services, Kafka, consumer services, and a data lake.',
    model: {
      people: [
        {
          id: 'analyst',
          type: 'person',
          name: 'Data Analyst',
          description: 'Queries the data lake for business intelligence and reporting.',
          tags: ['Element', 'Person', 'Staff'],
          properties: {},
          location: 'Internal',
        },
      ],
      softwareSystems: [
        {
          id: 'eventPlatform',
          type: 'softwareSystem',
          name: 'Event-Driven Platform',
          description: 'The event-driven data processing platform.',
          tags: ['Element', 'Software System'],
          properties: {},
          location: 'Internal',
          containers: [
            {
              id: 'ingestService',
              type: 'container',
              name: 'Ingest Service',
              description: 'Receives data from external sources and publishes events.',
              technology: 'Python, FastAPI',
              tags: ['Element', 'Container', 'Producer'],
              properties: {},
              components: [],
            },
            {
              id: 'clickstreamService',
              type: 'container',
              name: 'Clickstream Collector',
              description: 'Captures user interaction events from web and mobile clients.',
              technology: 'Go',
              tags: ['Element', 'Container', 'Producer'],
              properties: {},
              components: [],
            },
            {
              id: 'kafka',
              type: 'container',
              name: 'Apache Kafka',
              description: 'Distributed event streaming platform and central message backbone.',
              technology: 'Apache Kafka',
              tags: ['Element', 'Container', 'Queue'],
              properties: {},
              components: [],
            },
            {
              id: 'enrichmentService',
              type: 'container',
              name: 'Enrichment Service',
              description: 'Consumes raw events, enriches with metadata, and re-publishes.',
              technology: 'Java, Kafka Streams',
              tags: ['Element', 'Container', 'Consumer'],
              properties: {},
              components: [],
            },
            {
              id: 'analyticsService',
              type: 'container',
              name: 'Analytics Service',
              description: 'Processes enriched events and generates aggregated metrics.',
              technology: 'Scala, Apache Flink',
              tags: ['Element', 'Container', 'Consumer'],
              properties: {},
              components: [],
            },
            {
              id: 'notificationService',
              type: 'container',
              name: 'Notification Service',
              description: 'Listens for specific events and sends alerts via email and push notifications.',
              technology: 'Node.js',
              tags: ['Element', 'Container', 'Consumer'],
              properties: {},
              components: [],
            },
            {
              id: 'dataLake',
              type: 'container',
              name: 'Data Lake',
              description: 'Long-term storage for raw and processed event data.',
              technology: 'AWS S3, Apache Parquet',
              tags: ['Element', 'Container', 'Database'],
              properties: {},
              components: [],
            },
          ],
        },
        {
          id: 'externalSource',
          type: 'softwareSystem',
          name: 'External Data Source',
          description: 'Third-party systems that push data into the platform.',
          tags: ['Element', 'Software System', 'External System'],
          properties: {},
          location: 'External',
          containers: [],
        },
      ],
      relationships: [
        { id: 'r1', sourceId: 'externalSource', destinationId: 'eventPlatform', description: 'Sends data to', tags: ['Relationship'], properties: {} },
        { id: 'r2', sourceId: 'analyst', destinationId: 'eventPlatform', description: 'Queries for reports', tags: ['Relationship'], properties: {} },
        { id: 'r3', sourceId: 'externalSource', destinationId: 'ingestService', description: 'Pushes data via webhooks', technology: 'HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r4', sourceId: 'ingestService', destinationId: 'kafka', description: 'Publishes raw events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r5', sourceId: 'clickstreamService', destinationId: 'kafka', description: 'Publishes clickstream events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r6', sourceId: 'kafka', destinationId: 'enrichmentService', description: 'Delivers raw events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r7', sourceId: 'enrichmentService', destinationId: 'kafka', description: 'Publishes enriched events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r8', sourceId: 'kafka', destinationId: 'analyticsService', description: 'Delivers enriched events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r9', sourceId: 'kafka', destinationId: 'notificationService', description: 'Delivers alert-worthy events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r10', sourceId: 'analyticsService', destinationId: 'dataLake', description: 'Writes aggregated data', technology: 'S3 API', tags: ['Relationship'], properties: {} },
        { id: 'r11', sourceId: 'enrichmentService', destinationId: 'dataLake', description: 'Archives enriched events', technology: 'S3 API', tags: ['Relationship'], properties: {} },
        { id: 'r12', sourceId: 'analyst', destinationId: 'dataLake', description: 'Queries for analytics', technology: 'SQL / Athena', tags: ['Relationship'], properties: {} },
      ],
      groups: [],
    },
    views: {
      systemLandscapeViews: [
        {
          type: 'systemLandscape',
          key: 'SystemLandscape',
          title: 'System Landscape',
          description: 'Overview of the event-driven platform.',
          elements: [
            { id: 'analyst' },
            { id: 'eventPlatform' },
            { id: 'externalSource' },
          ],
          relationships: [
            { id: 'r1' }, { id: 'r2' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      systemContextViews: [],
      containerViews: [
        {
          type: 'container',
          key: 'Containers',
          title: 'Containers',
          description: 'Producers, Kafka, consumers, and data lake.',
          softwareSystemId: 'eventPlatform',
          elements: [
            { id: 'analyst' },
            { id: 'externalSource' },
            { id: 'ingestService' },
            { id: 'clickstreamService' },
            { id: 'kafka' },
            { id: 'enrichmentService' },
            { id: 'analyticsService' },
            { id: 'notificationService' },
            { id: 'dataLake' },
          ],
          relationships: [
            { id: 'r3' }, { id: 'r4' }, { id: 'r5' }, { id: 'r6' },
            { id: 'r7' }, { id: 'r8' }, { id: 'r9' }, { id: 'r10' },
            { id: 'r11' }, { id: 'r12' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      componentViews: [],
      configuration: {
        styles: {
          elements: [
            { tag: 'Staff', background: '#1e2832', color: '#94a3b8', stroke: '#475569' },
            { tag: 'External System', background: '#201c28', color: '#c084fc', stroke: '#9333ea' },
            { tag: 'Producer', background: '#0e2a1a', color: '#6ee7b7', stroke: '#059669' },
            { tag: 'Consumer', background: '#2d0f0f', color: '#fca5a5', stroke: '#ef4444' },
            { tag: 'Queue', background: '#2d1f0d', color: '#fdba74', stroke: '#f97316' },
            { tag: 'Database', background: '#1e1a40', color: '#c4b5fd', stroke: '#7c3aed', shape: 'Cylinder' },
          ],
          relationships: [],
        },
      },
    },
  }
}
