import type { Workspace } from '@/types/model'

/** Microservices architecture — API gateway + services + message broker */
export function createMicroservicesTemplate(): Workspace {
  return {
    name: 'Microservices Architecture',
    description: 'An API gateway with microservices, message broker, and backing data stores.',
    model: {
      people: [
        {
          id: 'customer',
          type: 'person',
          name: 'Customer',
          description: 'A user of the platform who interacts via web or mobile.',
          tags: ['Element', 'Person', 'Customer'],
          properties: {},
          location: 'External',
        },
      ],
      softwareSystems: [
        {
          id: 'platform',
          type: 'softwareSystem',
          name: 'E-Commerce Platform',
          description: 'The microservices-based e-commerce platform.',
          tags: ['Element', 'Software System'],
          properties: {},
          location: 'Internal',
          containers: [
            {
              id: 'apiGateway',
              type: 'container',
              name: 'API Gateway',
              description: 'Routes requests to the appropriate microservice and handles authentication.',
              technology: 'Node.js, Express',
              tags: ['Element', 'Container'],
              properties: {},
              components: [],
            },
            {
              id: 'userService',
              type: 'container',
              name: 'User Service',
              description: 'Manages user accounts, authentication, and profiles.',
              technology: 'Java, Spring Boot',
              tags: ['Element', 'Container'],
              properties: {},
              components: [],
            },
            {
              id: 'orderService',
              type: 'container',
              name: 'Order Service',
              description: 'Handles order creation, tracking, and fulfilment.',
              technology: 'Java, Spring Boot',
              tags: ['Element', 'Container'],
              properties: {},
              components: [],
            },
            {
              id: 'productService',
              type: 'container',
              name: 'Product Service',
              description: 'Manages the product catalogue and inventory.',
              technology: 'Go',
              tags: ['Element', 'Container'],
              properties: {},
              components: [],
            },
            {
              id: 'postgres',
              type: 'container',
              name: 'PostgreSQL',
              description: 'Primary relational data store for users, orders, and products.',
              technology: 'PostgreSQL 15',
              tags: ['Element', 'Container', 'Database'],
              properties: {},
              components: [],
            },
            {
              id: 'redis',
              type: 'container',
              name: 'Redis',
              description: 'In-memory cache and session store.',
              technology: 'Redis 7',
              tags: ['Element', 'Container', 'Database'],
              properties: {},
              components: [],
            },
            {
              id: 'rabbitMQ',
              type: 'container',
              name: 'RabbitMQ',
              description: 'Message broker for asynchronous communication between services.',
              technology: 'RabbitMQ',
              tags: ['Element', 'Container', 'Queue'],
              properties: {},
              components: [],
            },
          ],
        },
      ],
      relationships: [
        { id: 'r1', sourceId: 'customer', destinationId: 'platform', description: 'Browses products, places orders', tags: ['Relationship'], properties: {} },
        { id: 'r2', sourceId: 'customer', destinationId: 'apiGateway', description: 'Makes API requests', technology: 'HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r3', sourceId: 'apiGateway', destinationId: 'userService', description: 'Routes auth requests', technology: 'gRPC', tags: ['Relationship'], properties: {} },
        { id: 'r4', sourceId: 'apiGateway', destinationId: 'orderService', description: 'Routes order requests', technology: 'gRPC', tags: ['Relationship'], properties: {} },
        { id: 'r5', sourceId: 'apiGateway', destinationId: 'productService', description: 'Routes product requests', technology: 'gRPC', tags: ['Relationship'], properties: {} },
        { id: 'r6', sourceId: 'userService', destinationId: 'postgres', description: 'Reads from and writes to', technology: 'SQL', tags: ['Relationship'], properties: {} },
        { id: 'r7', sourceId: 'orderService', destinationId: 'postgres', description: 'Reads from and writes to', technology: 'SQL', tags: ['Relationship'], properties: {} },
        { id: 'r8', sourceId: 'productService', destinationId: 'postgres', description: 'Reads from and writes to', technology: 'SQL', tags: ['Relationship'], properties: {} },
        { id: 'r9', sourceId: 'apiGateway', destinationId: 'redis', description: 'Caches sessions and tokens', technology: 'Redis Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r10', sourceId: 'orderService', destinationId: 'rabbitMQ', description: 'Publishes order events', technology: 'AMQP', tags: ['Relationship'], properties: {} },
        { id: 'r11', sourceId: 'productService', destinationId: 'rabbitMQ', description: 'Consumes inventory updates', technology: 'AMQP', tags: ['Relationship'], properties: {} },
        { id: 'r12', sourceId: 'userService', destinationId: 'rabbitMQ', description: 'Publishes user events', technology: 'AMQP', tags: ['Relationship'], properties: {} },
      ],
      groups: [],
    },
    views: {
      systemLandscapeViews: [
        {
          type: 'systemLandscape',
          key: 'SystemLandscape',
          title: 'System Landscape',
          description: 'Overview of the microservices platform.',
          elements: [
            { id: 'customer' },
            { id: 'platform' },
          ],
          relationships: [
            { id: 'r1' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      systemContextViews: [],
      containerViews: [
        {
          type: 'container',
          key: 'Containers',
          title: 'Containers',
          description: 'The microservices, data stores, and message broker.',
          softwareSystemId: 'platform',
          elements: [
            { id: 'customer' },
            { id: 'apiGateway' },
            { id: 'userService' },
            { id: 'orderService' },
            { id: 'productService' },
            { id: 'postgres' },
            { id: 'redis' },
            { id: 'rabbitMQ' },
          ],
          relationships: [
            { id: 'r2' }, { id: 'r3' }, { id: 'r4' }, { id: 'r5' },
            { id: 'r6' }, { id: 'r7' }, { id: 'r8' }, { id: 'r9' },
            { id: 'r10' }, { id: 'r11' }, { id: 'r12' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      componentViews: [],
      configuration: {
        styles: {
          elements: [
            { tag: 'Database', background: '#1e1a40', color: '#c4b5fd', stroke: '#7c3aed', shape: 'Cylinder' },
            { tag: 'Queue', background: '#2d1f0d', color: '#fdba74', stroke: '#f97316' },
          ],
          relationships: [],
        },
      },
    },
  }
}
